# Generated by Django 3.2.10 on 2021-12-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auth',
            new_name='author',
        ),
    ]
